### ISSUE TITLE
Move the factories inside the ecs package?

### ISSUE THREAD

**Issue by Trulsmatias** [Jonas-C/TDT4240-Gaalf#41]

**Comment by Trulsmatias** [comment]
After doing some research. Is doesn't look like it matter too much, but that it is recommended. There are some disagreements though. Read this for further details: https://stackoverflow.com/questions/1894102/how-to-package-factories-in-java

**Comment by Jonas-C** [comment]
@Trulsmatias Seeing as you're the most knowledgeable on the subject I think it should be your call.
